### PR TITLE
enable sriov-cni on arm platform

### PR DESCRIPTION
**Pull request by lubinsz**
Currently, sriov-cni can't be build on arm64 platform
due to the undefined error in the library of golang during the compilation step.
such as:

./build
Building plugins
gopath/src/github.com/hustcat/sriov-cni/vendor/golang.org/x/sys/unix/flock.go:18: undefined: Flock_t

We should upgrade the version of 'golang.org/x/sys' and cni,
so that this issue will be gone.

Signed-off-by: Bin Lu <bin.lu@arm.com>

### CODE REVIEW

**Comment by lubinsz** [comment]
Full err log on arm64 platform as reference: 

root@entos-arm-03:/go/src/github.com/hustcat/sriov-cni# ./build
Building plugins
#github.com/hustcat/sriov-cni/vendor/golang.org/x/sys/unix
gopath/src/github.com/hustcat/sriov-cni/vendor/golang.org/x/sys/unix/flock.go:18: undefined: Flock_t
gopath/src/github.com/hustcat/sriov-cni/vendor/golang.org/x/sys/unix/sockcmsg_linux.go:14: undefined: Ucred
gopath/src/github.com/hustcat/sriov-cni/vendor/golang.org/x/sys/unix/sockcmsg_linux.go:27: undefined: Ucred
gopath/src/github.com/hustcat/sriov-cni/vendor/golang.org/x/sys/unix/sockcmsg_unix.go:42: undefined: Cmsghdr

**Comment by lubinsz** [comment]
@rkamudhan 
@hustcat 
Hi all,
Please have a look. Thanks.

**Comment by rkamudhan** [comment]
@lubinsz Why there is the need to change the vendor file ?

**Comment by lubinsz** [comment]
Hi @rkamudhan 
Because cni:v0.3.0 ~ cni:v0.3.0-rc3 can't be build on arm platform. And this bug was fixed in v0.4.0.
If we want to enable sriov-cni on arm platform, we should upgrade the version of cni in the vendor firstly.

For your reference, the error log of cni:v0.3.0-rc3 :
1, cni:v0.3.0-rc3  can't be build on arm platform;
     a, check version

       root@Xenial:/go/src/github.com/containernetworking/cni# git branch
      * (HEAD detached at v0.3.0-rc3)
       master

       b, build
        root@Xenial:/go/src/github.com/containernetworking/cni# ./build
        Building API
        Building reference CLI
        Building plugins
        flannel
        tuning
        #github.com/containernetworking/cni/vendor/golang.org/x/sys/unix
        gopath/src/github.com/containernetworking/cni/vendor/golang.org/x/sys/unix/flock.go:18: undefined: Flock_t
   gopath/src/github.com/containernetworking/cni/vendor/golang.org/x/sys/unix/sockcmsg_linux.go:14: undefined: Ucred
   gopath/src/github.com/containernetworking/cni/vendor/golang.org/x/sys/unix/sockcmsg_linux.go:27: undefined: Ucred
   gopath/src/github.com/containernetworking/cni/vendor/golang.org/x/sys/unix/sockcmsg_unix.go:42: undefined: Cmsghdr

2, same issue with sriov-cni:

root@entos-arm-03:/go/src/github.com/hustcat/sriov-cni# ./build
Building plugins
#github.com/hustcat/sriov-cni/vendor/golang.org/x/sys/unix
gopath/src/github.com/hustcat/sriov-cni/vendor/golang.org/x/sys/unix/flock.go:18: undefined: Flock_t
gopath/src/github.com/hustcat/sriov-cni/vendor/golang.org/x/sys/unix/sockcmsg_linux.go:14: undefined: Ucred
gopath/src/github.com/hustcat/sriov-cni/vendor/golang.org/x/sys/unix/sockcmsg_linux.go:27: undefined: Ucred
gopath/src/github.com/hustcat/sriov-cni/vendor/golang.org/x/sys/unix/sockcmsg_unix.go:42: undefined: Cmsghdr

**Comment by hustcat** [comment]
@lubinsz I don't have ARM environment. Do you mean only need update `vendor` to make  build success on the ARM platform ?

**Comment by lubinsz** [comment]
@hustcat 
As a result of the version changes, in addition to the change of **vendor**, there is only one change that we should notice:
In this patch, I only modified two files by myself: fixipam/main.go & sriov/sriov.go.
Because the definition of 'skel.PluginMain' was changed, we should add a new input for it.
Please see it as reference:
old version: skel.PluginMain(cmdAdd, cmdDel)
New version: skel.PluginMain(cmdAdd, cmdDel, **version.Legacy**)

**Comment by lubinsz** [comment]
@hustcat 
Hi, 
How is the progress?

**Comment by lubinsz** [comment]
@hustcat @rkamudhan 
Hi all, 
Now, I'm plan to enable sriov-cni with OPNFV(installer: Compass).
So could you take a look at this issue? We can't enable sriov-cni with OPNFV@Arm without this PR.
Thanks

**Comment by hustcat** [comment]
@lubinsz Sorry about the delay. l will spend time to take a look at this PR at the next two days.

**Comment by hustcat** [comment]
LGTM, @rkamudhan @ahalim-intel  Could you like to take a look at this PR?

**Comment by ahalimx86** [comment]
LGTM

**Pull request merged**
